export const bundeslandDict = {
    Burgenland: 'Bgld',
    Kärnten: 'Ktn',
    Niederösterreich: 'NÖ',
    Oberösterreich: 'OÖ',
    Salzburg: 'Sbg',
    Steiermark: 'Stmk',
    Tirol: 'T',
    Vorarlberg: 'Vbg',
    Wien: 'W',
    'Österreich gesamt': 'Ö',
    "Bgld.": 'Bgld',
    "Kt.": 'Ktn',
    "NÖ": 'NÖ',
    "OÖ": 'OÖ',
    "Sbg.": 'Sbg',
    "Stmk.": 'Stmk',
    "T": 'T',
    "Vbg.": 'Vbg',
    "W": 'W',
    "Österreich": 'Ö'
}
